### ISSUE TITLE
Breaks Polymer DevTools Extension

### ISSUE THREAD

**Issue by sfeast** [joshheinrichs/iron-scroll-threshold#1]
When running an app with DevTools enabled (https://chrome.google.com/webstore/detail/polymer-devtools-extensio/mmpfaamodhhlbadloaibpocmcomledcg) & this component as part of the DOM the dev tool gives the following error:

Uncaught TypeError: Cannot read property 'toString' of undefined

**Comment by joshheinrichs** [comment]
Interesting, I was not aware of this extension. Thanks for the fix!

**Comment by sfeast** [comment]
Thanks!
